### ISSUE TITLE
Mif-file generation broken

### ISSUE THREAD

**Issue by lang-m** [ubermag/oommfc#108]
The changes in `micromagneticmodel.term.__contains__` (checking for all attributes) introduced in ubermag/micromagneticmodel#46 breaks the `mif` file generation. In `driver.py:driver_script` we use `mm.Damping() in system.dynamics` tests (similar for `mm.Precession`). Without the correct arguments these tests fail and we write wrong `alpha` values to the `mif` file.

**Comment by marijanbeg** [comment]
Although physically probably it does not make sense to have two damping terms, I would not exclude that possibility in `mm`. The reason is to allow full flexibility for any calculators that can be built on top of `mm`. I believe damping terms just like energy terms have names already. Instead of `mm.Damping() in system.dynamics`, we could have `if any(isinstance(term, mm.DynamicsTerm) for term in system.dynamics):...`. Does that make sense?

**Comment by marijanbeg** [comment]
Similarly, when we check if a term has a unique name, we could ask for: `if term.name not in [i.name for i in system.energy]: add the term to the container`.

**Comment by lang-m** [comment]
I think it would be nice to encapsulate that functionality to avoid all the hard-to-understand if statements.
@swapneelap and I had a discussion and decided to add two additional methods:
```python
>>> system.dynamics = mm.Damping(alpha=1)
>>> system.dynamics.contains_by_type(mm.Damping)
True
>>> system.dynamics.get_by_type(mm.Damping)
[mm.Damping(alpha=1)]
```

Instead of `contains_by_type` we could generalise `__contains__` to accept a type:
```python
>>> system.dynamics = mm.Damping(alpha=1)
>>> mm.Damping() in system.dynamics  # wrong alpha
False
>>> mm.Damping in system.dynamics
True
```
but we think that this is to "dangerous" because the difference is very subtle.

@marijanbeg Does that sound okay?

**Comment by marijanbeg** [comment]
Yes, I like this idea, and also agree that extending `in` is too dangerous.

1. I do not like the names, e.g. `type` is a built-in and `contains` is too similar to `__contains__` special method.
1. Maybe `type` can be `cls`.
1. Maybe `contains` can be `contains_cls`
1. What if there are multiple terms of the same class, e.g. `Zeeman`? Do you get a `Container` as the result? Is the result always the container or it can be a term object?
1. I am wondering if `get` is redundant. For instance, `if not system.dynamics.get(cls=mm.Damping)` can be trythy/falsy.

There are no right/wrong answers here - just some topics to think about. Whatever you decide, I would be happy with :)

**Comment by marijanbeg** [comment]
1. +1
3. +1
4. +1
5. Yes, I meant contains is not necessary :)
