### ISSUE TITLE
Request for some indication for not using dynamics equation when using TimeDriver()

### ISSUE THREAD

**Issue by kzqureshi** [ubermag/oommfc#143]
The simulation "runs" but nothing happens.

**Comment by swapneelap** [comment]
Do I understand correctly that you want to raise an error/warning when one runs a `TimeDriver` in the absence of `system.dynamics` term(s)?

**Comment by kzqureshi** [comment]
> Do I understand correctly that you want to raise an error/warning when one runs a `TimeDriver` in the absence of `system.dynamics` term(s)?
 Yes, you understand correctly
> Also, what exactly do you mean by "nothing happens"? Do you mean that `system.m` does not update or the simulation continues endlessly?
`system.m` does run but the inital state does not change after `TimeDriver` as `system.dynamics` were not mentioned.

**Comment by swapneelap** [comment]
Okay I understand. I have three questions:
1. Should we raise an error/warning if OOMMF is OK with running a time driver with no dynamics term?
2. I am leaning towards raising a warning. I think raising an error would be too strong a stance. Does this sound reasonable?
3. If we implement this in `oommfc`, it would good to know what mumax3 does in such a situation and maybe raise an error/warning in `mumax3c` as well for consistency. Does this sound reasonable? 

It would be good to know @lang-m, @samjrholt, @fangohr opinions.

**Comment by kzqureshi** [comment]
Done in #151
