### ISSUE TITLE
save magnetisation data at every field value in hysteresis loop

### ISSUE THREAD

**Issue by Shonnali** [ubermag/oommfc#145]
Hi,
Thank you very much Ubermag team for a nice project. I have a question, how is it possible for me to save the magnetisation data at every field value during the hysteresis loop recording. 

In addition is it also possible to apply an external field at say a small angle with respect to x,y,z axis?

**Comment by lang-m** [comment]
Do you use the `HysteresisDriver` documented here: https://ubermag.github.io/examples/notebooks/hysteresis.html ? Then your magnetisation data should automatically be saved during each hysteresis step.

Adding a second external field is supported, it is documented here: https://ubermag.github.io/examples/notebooks/multiple-terms.html

**Comment by Shonnali** [comment]
Thanks Martin, yes I use the hysteresis driver. What I meant was, is there a method to save the images of the magnetisation state of the sample at each point during the hysteresis loop measurement? 

Regarding the second question, I dont want to use a second external field, but just a field, say at 5 degrees with respect to x axis and then measure hysteresis, so as to break any symmetry effects which arise due to meshing.

**Comment by lang-m** [comment]
Regarding image saving: you can create those after the simulation has finished using micromagneticdata: https://ubermag.github.io/documentation/notebooks/micromagneticdata/documentation.html

The direction of your hysteresis field depends on the vectors you use for `Hmin` and `Hmax` in the `HysteresisDriver`, which can have arbitrary orientation in space, see the documentation notebook in my previous reply.

**Comment by Shonnali** [comment]
OK, many thanks Martin. Have a great day and a great week ahead.
