### ISSUE TITLE
Question about open boundary conditions seem to not working?

### ISSUE THREAD

**Issue by dovod91** [ubermag/oommfc#162]
Hello team,

I have a question about the open boundary conditions. I naturally assume these are 'perfect' absorbers, however, in the following picture at timestep 112, I can see reflections at the borders of my simulated box (see x = 0).  The source is a localized region at x = 50. The mesh settings are:

`mesh = df.Mesh(region=region, cell=cell, subregions=subregions, bc='')`

I am assuming open boundaries are set correctly, so I cannot see what might be wrong with my mesh. Subregions are shown here too, but I don't think they are an issue... many thanks for any insight of what I could check next!

![image](https://github.com/user-attachments/assets/b7a7e781-660e-4788-b9bc-5b2ed8a203d1)
![image](https://github.com/user-attachments/assets/61d631b3-971a-4b22-ab38-86ed1f95dc78)

**Comment by fangohr** [comment]
> I have a question about the open boundary conditions. I naturally assume these are 'perfect' absorbers, however, in the following picture at timestep 112, I can see reflections at the borders of my simulated box (see x = 0).

It is not clear to me why open boundary conditions should be perfect absorbers.

There is a paper suggesting change of damping at the edge to suppress reflections: https://doi.org/10.1016/j.jmmm.2017.06.057
