### ISSUE TITLE
Can we find and display OOMMF log file on oommf failure?

### ISSUE THREAD

**Issue by fangohr** [ubermag/oommfc#29]
In a situation like https://travis-ci.org/joommf/oommfc/builds/342456366#L1672, it might be useful to display the OOMMF log file, which gives an indication for what error OOMMF fails. In the particular example of this run on travis, it is likely that OOMMF failed because we use the wrong name for the DMI interaction in the mid file (the OOMMF C code has been updated, but is using the 'old' OOMMF binary that doesn't support the new extension yet). 

While this situation should not occur, it will be very useful for similar changes and version conflicts in the future.

**Comment by marijanbeg** [comment]
This is now implemented on master.
