### ISSUE TITLE
LaTeX output. doesn't render in readthedocs

### ISSUE THREAD

**Issue by fangohr** [ubermag/oommfc#34]
Output cells 5 and 6 on https://oommfc.readthedocs.io/en/latest/ipynb/spatially_varying_parameters.html#Spatially-varying-parameters show LaTeX source instead of the rendered equations.

Probably not specific to OOMMFC, but here we have an example.

$\frac{\partial \mathbf{m}}{\partial t}=-\gamma_{0}^{*} \mathbf{m} \times \mathbf{H}_\text{eff}+\alpha \mathbf{m} \times\frac{\partial \mathbf{m}}{\partial t}$

**Comment by marijanbeg** [comment]
Fixed
