### ISSUE TITLE
import oommfc as oc error

### ISSUE THREAD

**Issue by Zulfidin** [ubermag/oommfc#45]
The error message is attached:
<img width="901" alt="Screen Shot 2019-08-21 at 23 30 58" src="https://user-images.githubusercontent.com/21960382/63486125-ceb4a200-c46b-11e9-8dcf-5761f94c15e5.png">

**Comment by Ponsudana** [comment]
Hi @Zulfidin,

I don't know about the errors, but I wish to help.

Have you done the testing after installing joommf?
[oommfc.pdf](https://github.com/ubermag/oommfc/files/3528536/oommfc.pdf)

**Comment by marijanbeg** [comment]
Hi @Zulfidin, thank you for using `oommfc`. At the moment we are in the middle of major updates to all our packages, and the new release of `oommfc` will be done by the end of the week. Until that is done, and if you want to use it urgently, you can install `oommfc` from source, by running:

    $ pip install git+git://github.com/ubermag/oommfc.git

In addition to that, please also install `oommf` via conda, because this dependency cannot be packaged via pip.

    $ conda install --channel conda-forge oommf

I will close this issue now, but if you need any further support on this matter, please feel free to reopen it.

@Ponsudana, Thank you again for supporting other users. Much appreciated!

**Comment by Zulfidin** [comment]
> Hi @Zulfidin,
> 
> I don't know about the errors, but I wish to help.
> 
> Have you done the testing after installing joommf?
> [oommfc.pdf](https://github.com/ubermag/oommfc/files/3528536/oommfc.pdf)

It gave the same error when it was tested.

**Comment by Zulfidin** [comment]
> Hi @Zulfidin, thank you for using `oommfc`. At the moment we are in the middle of major updates to all our packages, and the new release of `oommfc` will be done by the end of the week. Until that is done, and if you want to use it urgently, you can install `oommfc` from source, by running:
> 
> ```
> $ pip install git+git://github.com/ubermag/oommfc.git
> ```
> 
> In addition to that, please also install `oommf` via conda, because this dependency cannot be packaged via pip.
> 
> ```
> $ conda install --channel conda-forge oommf
> ```
> 
> I will close this issue now, but if you need any further support on this matter, please feel free to reopen it.
> 
> @Ponsudana, Thank you again for supporting other users. Much appreciated!

Thank you for your comments,

So, I did these steps:
1. `$ conda create -n mumax_3 python=3.5`
2. `$ conda activate mumax_3` 
3. `$ pip install git+git://github.com/ubermag/oommfc.git`
4. `conda install --channel conda-forge oommf`

Then, it was still not able to import oommf:

<img width="1018" alt="Screen Shot 2019-08-22 at 11 37 34" src="https://user-images.githubusercontent.com/21960382/63532890-5254aa00-c4d1-11e9-973a-2c2c07cad420.png">

**Comment by fangohr** [comment]
The anaconda distribution has installed python 3.5 for you. You need at least python 3.6 for übermag to work. 

The latest anaconda distribution provides 3.6.

**Comment by marijanbeg** [comment]
I agree with @fangohr. Please choose Python 3.6 or higher. For instance,

    $ conda create -n mumax_3 python=3.7

**Comment by Zulfidin** [comment]
> The anaconda distribution has installed python 3.5 for you. You need at least python 3.6 for übermag to work.
> 
> The latest anaconda distribution provides 3.6.

Yes, it worked. Thank you @marijanbeg  too.
