### ISSUE TITLE
import oommf error 

### ISSUE THREAD

**Issue by Zulfidin** [ubermag/oommfc#46]
I followed the instructions that was given to me,

So, I did these steps:

1. `$ conda create -n mumax_3 python=3.5`
2. `$ conda activate mumax_3` 
3. `$ pip install git+git://github.com/ubermag/oommfc.git`
4. `conda install --channel conda-forge oommf`

Then, it was still not able to import oommf:

<img width="1018" alt="Screen Shot 2019-08-22 at 11 37 34" src="https://user-images.githubusercontent.com/21960382/63532890-5254aa00-c4d1-11e9-973a-2c2c07cad420.png">

**Comment by marijanbeg** [comment]
Please choose a higher version of Python:

    conda create -n mumax_3 python=3.7

**Comment by marijanbeg** [comment]
As reported by @Zulfidin, this problem is now fixed.
