### ISSUE TITLE
how to use Ubermag docker image with Jupyter notebook 

### ISSUE THREAD

**Issue by Baratjan** [ubermag/oommfc#49]
Dear developers, 

I tried pulling "docker pull ubermag/oommf:latest" and running it on Windows pc. It seems all fine, but I prefer running it on Jupyter with all matlibplot, numpy etc. libs just as we use it on Binder, rather than working on the terminal. I also docked Jupyter notebook, and I can run it on my browser. I got now stuck on how to combine the two, so that when I run a 'merged' image for example, oommfc,  discretisedfiel, matplotlib, numpy etc can be imported on Jupyter notebook. Could you guys help me on this? Many thanks in advance!

**Comment by marijanbeg** [comment]
Hi @Baratjan, thank you for your question. You can build a new docker image based on `ubermag/oommf:latest` to include ubermag (install ubermag using pip). The Dockerfile would be for example:

```
FROM ubermag/oommf

USER root

RUN apt update -y
RUN apt install -y git python3-pip curl
RUN python3 -m pip install --upgrade pip ubermag

USER oommfuser
```

This could be an interesting use-case to run the entire ubermag inside docker, so when you complete the solution, we can include the docker image in our repository.

**Comment by Baratjan** [comment]
Thanks very much Marijan. Sadly, I am still having problem running jupyter properly. The docker image build using above code is fine i think, I could run simulations using ipython in the container (after running the image using: docker run -it myUbermag_image /bin/bash). However, when I run: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root, it starts the server, but when I open the browser using the generated address, it does not show the notebook (ERR_EMPTY_RESPONSE). Am I missing anything here? (I also tried to force reinstall the jupyter in the container, did not help either. Did a bit google searching, tried few more things, none of them helping) Thanks very much in advance!

**Comment by Baratjan** [comment]
problem solved (I should not have called jupyter from container):
docker run --rm -p 8888:8888 -v c:/path/to/workfolder/:/path/in/container/:rw image-name:image-tag jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root

in my case (ubermag image), container path is /io, then the workfolder is mounted at the right place. 

All sorted:))) thanks again for your wonderful work!
