### ISSUE TITLE
Question: Visualization of k3d mesh not the same as tutorial

### ISSUE THREAD

**Issue by trcote** [ubermag/oommfc#51]
OS Catalina 10.15.6
python                    3.8.5

I'm wondering if you know or if it is important why the k3d visualized mesh for the tutorial is not the same as what is showing up in Jupyter Notebook? I installed with conda-forge, with no errors but some warnings. Everything else seems to be working correctly for what I have tested thus far. I tried uninstalling and reinstalling the newest Ubermag installation through conda-forge. Same thing happens.

Tutorial:
<img width="762" alt="Screen Shot 2020-09-22 at 11 50 52 AM" src="https://user-images.githubusercontent.com/17915743/93912835-e0e5bd00-fcc9-11ea-8d98-a40fc7c7fa10.png">

Jupyter Notebook Test:
<img width="1081" alt="Screen Shot 2020-09-22 at 11 51 50 AM" src="https://user-images.githubusercontent.com/17915743/93912916-02df3f80-fcca-11ea-841f-d1c82d0e9029.png">

**Comment by code-whale** [comment]
@trcote Hi,I also encountered this situation when I first started learning ubermag. Did you use the Safari browser for simulation? It seems that this is the case when Safari runs k3d. You can try it with Google browser:)

**Comment by trcote** [comment]
> @trcote Hi,I also encountered this situation when I first started learning ubermag. Did you use the Safari browser for simulation? It seems that this is the case when Safari runs k3d. You can try it with Google browser:)

Worked like a charm, hard part was getting jupyter to open in Chrome instead of Safari!

**Comment by marijanbeg** [comment]
Thank you @code-whale for helping :)
