### ISSUE TITLE
Support for Xf_ThermSpinXferEvolve

### ISSUE THREAD

**Issue by fgr1986** [ubermag/oommfc#52]
Hi!
Is there any kind of support for Xf_ThermSpinXferEvolve?
https://kelvinxyfong.wordpress.com/research/research-interests/oommf-extensions/oommf-extension-xf_thermspinxferevolve/

Thanks

**Comment by marijanbeg** [comment]
Thank you for your question. We do not support this OOMMF extension at the moment. However, this is something we can try to include in the next release.

Also, please feel free to contribute to the code and write that extension yourself :)

**Comment by marijanbeg** [comment]
This is implemented in #57 and will be included in the next release.

**Comment by marijanbeg** [comment]
Hi @fgr1986, what do you mean by "validated"? Have you discovered any issues? Is it on the Ubermag side or on OOMMF side?

**Comment by fgr1986** [comment]
> Thanks. You can see where their implementations come from in the docs:
> 
>     * https://github.com/ubermag/oommfc/blob/master/oommfc/evolvers/uhh_thetaevolver.py
> 
>     * https://github.com/ubermag/oommfc/blob/master/oommfc/evolvers/xf_thermspinxferevolver.py
> 
> 
> If there is a large (and unexpected) difference in the result between the two with the same parameters, then it could be:
> 
>     * the extensions use different names for the same thing or the units are very different
> 
>     * the extensions in OOMMF don't work as claimed
> 
> 
> I would suggest you make a comparison between the original docs for those two extensions if you spot anything suspicious.

Maybe it has to do with units... but indeed, neither of the 3 thermal evolvers give, to my understanding, valid behaviors.
Every single one of them lead to that kind of unexpected magnetic equilibrium, even at T=1K, which clearly differ from the same behavior at T=0K.

How could you advise to proceed? is any mode in ubermag that support finite temperature simulations?

Thanks

**Comment by marijanbeg** [comment]
In docstrings of implementations, there are links to those OOMMF extension documentations. I think the first step would be attempting to understand them. In particular, what each parameter is, what units are expected, etc.
