### ISSUE TITLE
How can I install oommfc    ???

### ISSUE THREAD

**Issue by sediEmad** [ubermag/oommfc#58]
**Hello, 
I am new to working with the software and trying to learn OOMMF by following the Tutorials.
I tried to install Anaconda and run oommfc.
After running oommfc by this command:  conda install --channel conda-forge oommfc
I got the following message:**

============================= warnings summary =====================================
anaconda3\envs\EMADI\lib\site-packages\pyreadline\py3k_compat.py:8
  C:\Users\emadi\anaconda3\envs\EMADI\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    return isinstance(x, collections.Callable)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
==================== 81 passed, 6 skipped, 1 warning in 760.12s (0:12:40) =========================

**and also when I import oommfc in python, I got the error message:** 
**ModuleNotFoundError: No module named 'oommfc'**
**How can I install oommfc?**
**Can someone help me out, please?**

**Many thanks in advance**
**sedighe**

**Comment by marijanbeg** [comment]
Hi @sediEmad, thank you for your question. Have you followed one of the installation tutorials from our YouTube channel https://www.youtube.com/channel/UC7MSqVQSMFV42R1jAYmKGLg? It seems all tests pass and `oommfc` is installed, but probably you start Jupyter from the wrong conda environment.

**Comment by sediEmad** [comment]
Hi Marijan Beg, I wish to be safe and healthy. Thank you for your response.I
have followed the  installation, testing, and update tutorials from:
https://oommfc.readthedocs.io/en/latest/ipynb/installation-testing-update.html
that is like installation tutorials from your YouTube channel (Ubermag
installation (Windows, miniconda)).

Sorry for the mistake in the previous email, maybe I should have said that I
got this error: Solving environment

(base) C:\Users\emadi>conda activate EMADI
(EMADI) C:\Users\emadi>conda install --channel conda-forge oommfc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json, will
retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

Thank you very much if you can help me.

Best regards

**Comment by sediEmad** [comment]
Hi Marijan Beg, I wish to be safe and healthy. Thank you for your response.
I have followed the  installation, testing, and update tutorials from:
https://oommfc.readthedocs.io/en/latest/ipynb/installation-testing-update.html
that is like installation tutorials from your YouTube channel (Ubermag installation (Windows, miniconda)).

Sorry for the mistake in the previous email, maybe I should have said that I got this error: Solving environment

(base) C:\Users\emadi>conda activate EMADI
(EMADI) C:\Users\emadi>conda install --channel conda-forge oommfc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

Thank you very much if you can help me.

Best regards

**Comment by marijanbeg** [comment]
Hi @sediEmad, thank you for the clarification. There is no error in the message you got (`Solving environment: done`). Have you tried running Jupyter notebook from `EMADI` environment?

**Comment by lang-m** [comment]
Hi @sediEmad, I could reproduce your error locally. Conda is installing an outdated version of `oommfc` (0.8.8). In order to install the latest version you will need to specify the version number.
If possible, create a fresh environment and then run:

    conda install -c conda-forge oommfc=0.10.1

(If you really need to keep the current environment you first have to remove oommfc and then update Python)

_NOTE_: In general our examples use several subpackages of `ubermag` (one of which is `oommfc`). You might want to install `ubermag` instead of `oommfc` (in a fresh environment):

    conda install -c conda-forge ubermag

 Thereby the correct version of `oommfc` will be installed automatically.

**Comment by sediEmad** [comment]
Hi dear @Marijan Beg
Thank you for your fast and kind reply. The problem was solved. As you
guided me in the beginning, I made a funny and bad mistake, the oommfc
installed
in one conda environment but I started Jupyter from the wrong conda environment
that their names were very similar.
Thanks again for your time.

**Comment by marijanbeg** [comment]
Great, thank you @sediEmad for the update.

@lang-m, thanks a lot for helping others.
