### ISSUE TITLE
macrospin.mif not readable when using docker runner with `selinux`

### ISSUE THREAD

**Issue by mjoelln** [ubermag/oommfc#95]
When using docker as a runner for oommf, macrospin.mif is not readable. I'm using Linux (Fedora 35). The issue seems to be, that the mounted volume in the docker container lacks read/write permission. I could resolve the issue by adding a ":z" in line 345 to the volume mounting in the oommf.py (in the _call function of DockerOOMMFRunner).
I suggest the line 345 to be like this: `cmd = [self.docker_exe, 'run', '-v', os.getcwd()+':/io:z'`,
I was not sure how to directly suggest this as a change instead of opening an issue, for me it is resolved with this change. Maybe someone can try if this breaks some functionality for MacOS.

**Comment by mjoelln** [comment]
Hi! Yes the selinux mode is "enforced" in my case. I also found several posts suggesting, that this is caused by selinux. 
Maybe there is also another option instead of using ":z" as the use of it can cause trouble, especially when mounting /home or /usr, as permissions can be changed on the host system. Unfortunately I don't have a better suggestion at the moment.

**Comment by lang-m** [comment]
As the `:z` option can cause side effects we should not generally add it.
We could check for `selinux` and add `:z` if `selinux` is enabled.

@mjoelln I assume you have issues with all simulations, not just the macrospin example?

**Comment by mjoelln** [comment]
Sorry, I should have been a little more detailed of when the issue arises. For me this is already occurs when choosing Docker as a Runner. `oommfc.runner.runner = oommfc.oommf.DockerOOMMFRunner(image='oommf/oommf:latest') `. I believe the initialization asks for the `runner.status` which runs the TimeDriver for 1 ms for `macrospin.mif` to check the functionality. Thus I could not try any other examples.

However, the issue occurs already when running just the docker container `oommf/oommf`. When running the following command to enter the docker container interactively: `docker run -v /home/_user_/Test:/io -it oommf/oommf:latest sh`, not even listing ( `ls` )the content of the bind mounted directory `/io` is possible, with this error: `ls: cannot open directory '.': Permission denied`. 

I tried two more options, one with success: `podman` instead of `docker` seems to run into the same issue.
Setting `selinux` to `permissive` by: `sudo setenforce Permissive` resolves the issue in my case!

Maybe as a start, without changing anything in `oommfc.py`, a comment in the ubermag documentation would be a good. For me, setting `selinux` temporarily to `permissive` is a solution which I can use for now. 
Alternatively, I could think of this as a solution: an optional argument (with False as a default) when choosing Docker as a runner would be nice. This way, adding the `:z` would be done deliberately by the user by setting that argument to True (maybe with a warning in the documentation).
